Repository Automattic/Rewrite-Rules-Inspector, pull requests merged in 2021-05, with the labels that each got.

#30 Create LICENSE
  LICENSE
Labels: Type: Maintenance

#21 Cleaned up code from #20
  rewrite-rules-inspector.php
Labels: Type: Maintenance

#35 Refresh WordPress.org assets
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-722x250.png
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  screenshot-1.jpg
  screenshot-2.jpg
Labels: Type: Maintenance

#27 Call get_rules() once and pass it to the list table
  rewrite-rules-inspector.php
Labels: bug

#36 Docs: Refresh README and add CHANGELOG file
  CHANGELOG.md
  README.md
  readme.txt
Labels: Type: Documentation

#37 Fix many coding standards violations
  rewrite-rules-inspector.php
  src/class-rewrite-rules-inspector-list-table.php
  src/class-rewrite-rules-inspector.php
Labels: Type: Maintenance

#38 Add PHPCS config file
  .gitignore
  .phpcs.xml.dist
  src/class-rewrite-rules-inspector-list-table.php
  src/class-rewrite-rules-inspector.php
Labels: Type: Maintenance
